import { NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/server";
import { verifyCallbackToken } from "@/lib/paymentHmac";

/**
 * bKash Payment Callback Handler
 *
 * SECURITY FIX: Verifies the HMAC token before performing any database write.
 * Without this check, any external actor could forge a payment confirmation by
 * hitting this endpoint with crafted query parameters (e.g., status=success,
 * feeId=<victim-fee-id>, amount=<any-amount>).
 *
 * The token is generated by paymentGateway.ts (server-side) and appended to
 * the redirect URL. It is a SHA-256 HMAC of "bkash:<feeId>:<amount>" using
 * the server-only PAYMENT_CALLBACK_SECRET env variable.
 */
export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const paymentID = searchParams.get("paymentID");
  const status = searchParams.get("status");
  const feeId = searchParams.get("feeId");
  const amountParam = searchParams.get("amount");
  const token = searchParams.get("token");

  const failureUrl = new URL("/student/fees", request.url);
  failureUrl.searchParams.set("payment", "cancel");

  if (status === "success" && feeId && amountParam) {
    const amount = Number(amountParam);

    // ── HMAC Verification ───────────────────────────────────────────────────
    // Reject immediately if token is missing or invalid.
    if (!verifyCallbackToken(token, "bkash", feeId, amount)) {
      console.warn("[bKash Callback] Invalid or missing HMAC token. Possible forgery attempt.", {
        feeId,
        amount,
        paymentID,
      });
      return NextResponse.redirect(failureUrl);
    }

    try {
      const supabase = createAdminClient();
      const nowIso = new Date().toISOString();

      const { error } = await supabase
        .from("fees")
        .update({
          status: "paid",
          amount_paid: amount,
          payment_method: "bkash",
          paid_at: nowIso,
          updated_at: nowIso,
        })
        .eq("id", feeId);

      if (error) {
        console.error("[bKash Callback] DB update error:", error.message);
        return NextResponse.redirect(failureUrl);
      }

      const redirectUrl = new URL("/student/fees", request.url);
      redirectUrl.searchParams.set("payment", "success");
      redirectUrl.searchParams.set("trxID", paymentID || `BKASH-${Date.now()}`);
      return NextResponse.redirect(redirectUrl);
    } catch (err) {
      console.error("[bKash Callback] Error updating fee record:", err);
    }
  }

  return NextResponse.redirect(failureUrl);
}
